services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_task_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  app:
    image: python:3.11-slim
    container_name: app_container
    build:
      context: .
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: [ "python", "run.py" ]
    depends_on:
      - postgres
    networks:
      - postgres_network
    env_file:
      - .env

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data: